[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "xrd-decosmic"
version = "1.2.0"
description = "Cosmic background removal from XRD 2d image"
authors = [
    { name = "Tianyi Cao", email = "ctyjackcao@outlook.com" }
]
dependencies = [
    "fabio==2024.9.0",
    "numpy==2.2.6",
    "scipy==1.15.3",
    "tqdm==4.67.1",
    "tifffile==2025.5.10",
    "pyfai==2025.3.0",
]
requires-python = ">=3.12,<3.13"
readme = "README.md"
license = { text = "MIT" }

[tool.hatch.build.targets.wheel]
packages = ["src/xrd_decosmic"]