[project]
name = "xrd-decosmic"
version = "1.0.0"
description = "Cosmic background removal from XRD 2d image"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pyFAI[all]",
    "numpy>=1.24.0",
    "matplotlib>=3.7.0",
    "scipy",
    "PySide6>=6.6.0",
    "fastapi>=0.109.0",
    "uvicorn>=0.27.0",
    "python-multipart>=0.0.6",
    "websockets>=12.0"
]
authors = [
    { name = "Tianyi Cao" }
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov"
]
dev = [
    "black",
    "isort",
    "flake8",
    "mypy"
]

[project.scripts]
xrd-decosmic = "decosmic.main:main"
xrd-decosmic-gui = "decosmic.gui.main:main"
xrd-decosmic-cli = "decosmic.cli.main:main"

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["decosmic"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"