[project]
name = "xrd-decosmic"
version = "1.0.0"
description = "Cosmic background removal from XRD 2d image"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["pyFAI[all]"]
authors = [
    { name = "Tianyi Cao" }
]

[tool.setuptools]
packages = ["decosmic"]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"