[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "xrd-decosmic"
version = "1.1.0"
description = "Cosmic background removal from XRD 2d image"
authors = [
    { name = "Tianyi Cao", email = "ctyjackcao@outlook.com" }
]
dependencies = [
    "fabio>=0.15.0",
    "numpy>=1.24.0",
    "scipy>=1.12.0",
    "tqdm>=4.66.0"
]
requires-python = ">=3.12"
readme = "README.md"
license = { text = "MIT" }

[tool.hatch.build.targets.wheel]
packages = ["src/xrd_decosmic"]